---
- name: Create compute instances
  hosts: localhost
  gather_facts: no
  roles:
    - compute_instance_creation  

- name: Config app machines
  hosts: label_role_wikijs
  gather_facts: no
  roles:
    - wikijs

- name: Config database machines
  hosts: label_role_db
  gather_facts: no
  roles:
   - database