- name: Install postgres
  apt:
    update_cache: true
    pkg:
    - postgresql
    - python3-psycopg2
    - libpq-dev
    - acl
    state: latest
  become: true

- name: Grant user wikijs permission
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/12/main/pg_hba.conf
    contype: host
    users: wikijs
    source: "0.0.0.0/0"
    databases: wiki
    method: md5
  become: true

- name: Set listen_addresses to all
  community.postgresql.postgresql_set:
    name: listen_addresses
    value: "*"
  register: set
  become: true
  become_user: postgres

- name: Restart postgres
  service:
    name: postgresql
    state: restarted
    enabled: true
  become: true

- name: "Create app database"
  postgresql_db:
    name: "{{ db_name }}"
    state: present
  become: true
  become_user: postgres

- name: "Create db user"
  postgresql_user:
    state: present
    name: "{{ db_user }}"
    password: "{{ db_passwd }}"
    db: "{{ db_name }}"
    priv: ALL
    role_attr_flags: NOSUPERUSER,NOCREATEDB
  become: true
  become_user: postgres