---

- name: Create a k8s namespace  
  kubernetes.core.k8s:    
    state: present    
    definition:      
      apiVersion: v1      
      kind: Namespace      
      metadata:        
        name: "{{ namespace }}"

- name: Create storage class
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: gold
      provisioner: kubernetes.io/gce-pd
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      reclaimPolicy: Delete
      parameters:
        type: pd-standard
        fstype: ext4
        replication-type: none      

- name: create pvc
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: webapps-storage
        namespace: wikijs
      spec:
        storageClassName: gold
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi

- name: Create mariadb service
  kubernetes.core.k8s:    
    state: present    
    definition: 
      apiVersion: v1
      kind: Service
      metadata:
        name: mariadb
        namespace: wikijs
      spec:
        selector:
          app: mariadb
        ports:
        - name: mariadb
          protocol: TCP
          port: 3306

- name: Create wikijs service
  kubernetes.core.k8s:    
      state: present    
      definition:
        apiVersion: v1
        kind: Service
        metadata:
          name: "wikijs"
          namespace: wikijs
        spec:
          type: LoadBalancer
          ports:
            - name: http
              port: 3000            
          selector:
            app: "wikijs"
        
- name: Create k8s pod for mariadb  
  kubernetes.core.k8s:    
    state: present    
    definition:      
      apiVersion: v1      
      kind: Pod      
      metadata:        
        name: "{{ db }}"        
        namespace: "{{ namespace }}"        
        labels:          
          app: "{{ db }}"      
      spec:        
        containers:
        - name: mariadb
          image: mariadb:10.4
          imagePullPolicy: Always
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb-secret
                key: PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: mariadb-secret
                key: DATABASE
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mariadb-secret
                key: USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb-secret
                key: PASSWORD
          ports:
          - containerPort: 3306
            name: mysql
          volumeMounts:
          - name: app-storage
            mountPath: /var/lib/mysql
        volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: webapps-storage

- name: Create k8s pod for wikijs
  kubernetes.core.k8s:    
    state: present    
    definition:      
      apiVersion: v1      
      kind: Pod      
      metadata:        
        name: "{{ app }}"        
        namespace: "{{ namespace }}"        
        labels:          
          app: "{{ app }}"      
      spec:        
        containers:          
          - name: "{{ app }}"            
            image: "{{ image }}"            
            imagePullPolicy: Always
            env: # Database ----
            - name: DB_TYPE
              value: "mariadb"
            - name: DB_HOST
              value: "mariadb"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: DATABASE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: PASSWORD

- name: Create secret for mariadb  
  kubernetes.core.k8s:    
    state: present    
    definition:      
      apiVersion: v1      
      kind: Secret      
      metadata:        
        name: mariadb-secret        
        namespace: "{{ namespace }}"        
      type: Opaque
      data:
        ROOT: b2xh
        DATABASE: d2lraWpz
        USER: d2lraWpz
        PASSWORD: b2xh
