- name: Create boot disks
  gcp_compute_disk:
    name: "disk-{{ item }}"
    state: present
    size_gb: 20
    source_image: "{{ source_img }}"
    zone: "{{ zone }}"
    project: "{{ project }}"
    auth_kind: "{{ auth_kind }}"
    service_account_file: "{{ service_account_file }}"
    scopes: "{{ scopes }}"
  loop:
    - wikijs
    - db
  register: disks


- name: Create IP address
  gcp_compute_address:
    name: "address-{{ item }}"
    project: "{{ project }}"
    auth_kind: "{{ auth_kind }}"
    service_account_file: "{{ service_account_file }}"
    scopes: "{{ scopes }}"
    region: "{{ region }}"
    state: present
  loop:
    - wikijs
    - db
  register: addresses

- name: Create an Instance
  gcp_compute_instance:
    state: present
    name: "{{ item }}"
    machine_type: "{{ machine_type }}"
    labels:
      role: "{{ item }}"
    disks:
      - auto_delete: true
        boot: true
        source: "{{ disks.results | selectattr('name', 'equalto', 'disk-' + item) | first }}"
    network_interfaces:
      - network: null
        access_configs:
          - name: 'External NAT'
            nat_ip: "{{ addresses.results | selectattr('name', 'equalto', 'address-' + item) | first }}"
            type: 'ONE_TO_ONE_NAT'
    zone: "{{ zone }}"
    project: "{{ project }}"
    auth_kind: "{{ auth_kind }}"
    service_account_file: "{{ service_account_file }}"
    scopes: "{{ scopes }}"
  loop:
    - wikijs
    - db
  register: instances